
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - clonesettrait.kruise_trait.v1alpha1
  resources:
  - traits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clonesettrait.kruise_trait.v1alpha1
  resources:
  - traits/status
  verbs:
  - get
  - patch
  - update
